[package]
org = "qaadir"
name = "backend"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "2.0.29"

# transitive dependency of org.apache.pdfbox:pdfbox:2.0.29
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "2.0.29"

# transitive dependency of org.apache.pdfbox:pdfbox:2.0.29
[[platform.java17.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.2"

# transitive dependency of org.apache.pdfbox:pdfbox:2.0.29
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcmail-jdk15to18"
version = "1.75"

# transitive dependency of org.bouncycastle:bcmail-jdk15to18:1.75
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15to18"
version = "1.75"

# transitive dependency of org.bouncycastle:bcmail-jdk15to18:1.75
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcutil-jdk15to18"
version = "1.75"

# transitive dependency of org.apache.pdfbox:pdfbox:2.0.29
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15to18"
version = "1.75"
